server:
  port: 8001

spring:
  devtools:
    restart:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-microservice:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile

jwt:
  secret: electrohogar

user:
  microservice:
    url: http://user-microservice:8002/api/v1/users

administration:
  microservice:
    url: http://administration-microservice:8003/api/v1/roles