server:
  port: 8021

tomcat:
  relaxed-query-chars: ["{", "}"]

spring:
  jackson:
    time-zone: America/Bogota

  datasource:
    url: jdbc:mysql://172.18.0.1:3306/cartera-temporal
    username: electrohogar
    password: GmjHog@r.2026*
    hikari:
      max-lifetime: 60000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    use_sql_comments: false

  http:
    encoding:
      charset: UTF-8
      force: true

  messages:
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-microservice:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30

user:
  microservice:
    url: http://user-microservice:8002/api/v1/users

clientes:
  temporal: http://clientes-microservice:8020/api/v1/clientes

auth:
  microservice:
    url: http://auth-microservice:8001/api/v1

ruta:
  firmas: /uploads/Firmas
  recibos: /uploads/Recibos